apiVersion: apps/v1
kind: Deployment
metadata:
  name: frauddetectionmodel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frauddetection
  template:
    metadata:
      labels:
        app: frauddetection
    spec:
      containers:
      - name: creditcard-fraud-detection-app
        image: gcr.io/mlops-poc-337511/creditcard_fraud_detection:v1
        ports:
        - containerPort: 9876