apiVersion: apps/v1
kind: Deployment
metadata:
  name: frauddetectionapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frauddetection
  template:
    metadata:
      labels:
        app: frauddetection
    spec:
      containers:
      - name: creditcard-fraud-detection-app
        image: gcr.io/mlops-poc-337511/app:v1
        ports:
        - containerPort: 8501